const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const seed={selectedAuctionId:"auction-1",auctions:[{id:"auction-1",name:"Johnson Farm & Estate Auction",type:"Mixed",date:"2026-10-10",location:"Lexington, Tennessee",status:"Cataloging",nextLot:129,items:[
{id:"lot-126",lot:126,title:"1937 John Deere AR Tractor",category:"Farm Equipment",condition:"Good used condition",startingBid:2500,description:"Two-cylinder row-crop tractor. Verify serial number, operating condition, and restoration history before publishing.",confidence:94,status:"Ready",photos:["assets/tractor.jpg"],createdAt:"2026-09-18T10:00:00Z"},
{id:"lot-127",lot:127,title:"Hand-carved French Oak Cabinet",category:"Antiques",condition:"Good used condition",startingBid:325,description:"Tall carved oak display cabinet with glazed door and fitted shelves. Inspect hardware and finish for age-related wear.",confidence:88,status:"Ready",photos:["assets/cabinet.jpg"],createdAt:"2026-09-18T10:10:00Z"},
{id:"lot-128",lot:128,title:"1972 Ford F-250 Pickup",category:"Vehicles",condition:"Fair",startingBid:1800,description:"Vintage Ford pickup. Verify VIN, mileage, title status, engine, and running condition before publishing.",confidence:91,status:"Ready",photos:["assets/truck.jpg"],vin:"",year:"1972",make:"Ford",model:"F-250",trim:"",body:"Pickup",engine:"",drive:"",mileage:"",createdAt:"2026-09-18T10:20:00Z"}]}]};
let state=null,route="dashboard",draftPhotos=[],working=false;

function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open("hammerlist-demo",1);r.onupgradeneeded=()=>r.result.createObjectStore("app");r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function loadState(){try{const d=await db();state=await new Promise((resolve,reject)=>{const t=d.transaction("app","readonly").objectStore("app").get("state");t.onsuccess=()=>resolve(t.result);t.onerror=()=>reject(t.error)});d.close()}catch{}if(!state)state=structuredClone(seed)}
async function saveState(){try{const d=await db();await new Promise((resolve,reject)=>{const t=d.transaction("app","readwrite").objectStore("app").put(state,"state");t.onsuccess=resolve;t.onerror=()=>reject(t.error)});d.close()}catch(e){showToast("Could not save on this device. Check available storage.")}}
function currentAuction(){return state.auctions.find(a=>a.id===state.selectedAuctionId)||null}
function showToast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),2800)}
function fmtDate(v){if(!v)return"Date not set";return new Date(`${v}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}
function money(v){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(v)||0)}
function setBusy(value,label="Working…"){working=value;[$("#scanBtn"),$("#secondOpinionBtn"),$("#scanVinBtn"),$("#decodeVinBtn")].forEach(b=>{b.disabled=value});if(value)showToast(label)}

function render(){const auction=currentAuction();$("#auctionSelect").innerHTML=state.auctions.length?state.auctions.map(a=>`<option value="${a.id}" ${a.id===state.selectedAuctionId?"selected":""}>${esc(a.name)}</option>`).join(""):`<option>No auctions yet</option>`;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));$("#mobileAdd").classList.toggle("hidden",!auction||route==="auctions");if(route==="auctions")renderAuctions();else if(!auction)renderNoAuction();else renderWorkspace(auction,route==="inventory")}
function renderNoAuction(){$("#mainContent").innerHTML=`<section class="setup-card"><div><p class="eyebrow">Get started</p><h2>Create your first auction</h2><p>Name the sale, choose its type, and HammerList will prepare the right catalog fields.</p><button class="btn primary" data-action="new-auction">Create auction</button></div></section>`}
function workflow(a){const total=a.items.length;const ready=a.items.filter(i=>i.status==="Ready").length;return`<div class="workflow-strip"><div class="workflow-step active"><strong>1</strong><span>Auction created</span></div><div class="workflow-step ${total?"active":""}"><strong>2</strong><span>Catalog items</span></div><div class="workflow-step ${ready&&ready===total?"active":""}"><strong>3</strong><span>Review lots</span></div><div class="workflow-step ${a.status==="Ready"?"active":""}"><strong>4</strong><span>Publish ready</span></div></div>`}
function renderWorkspace(a,inventoryOnly=false){const items=a.items||[],ready=items.filter(i=>i.status==="Ready").length,categories=new Set(items.map(i=>i.category)).size;$("#mainContent").innerHTML=`<header class="page-head"><div><p class="eyebrow">${esc(a.type)} auction</p><h1>${inventoryOnly?"Inventory":esc(a.name)}</h1><p class="muted">${inventoryOnly?esc(a.name):`${fmtDate(a.date)} · ${esc(a.location)}`}</p></div><div class="header-actions"><button class="btn secondary" data-action="auctions">Switch auction</button><button class="btn primary" data-action="add-item">＋ Add item</button></div></header>${inventoryOnly?"":workflow(a)}<div class="stats"><div class="stat"><small>Total lots</small><strong>${items.length}</strong></div><div class="stat"><small>Ready</small><strong>${ready}</strong></div><div class="stat"><small>Categories</small><strong>${categories}</strong></div><div class="stat"><small>Next lot</small><strong>#${a.nextLot}</strong></div></div><div class="content-grid"><section class="panel"><div class="panel-head"><h2>${inventoryOnly?"All inventory":"Recent inventory"}</h2><div class="filters"><input id="itemSearch" placeholder="Search lots"><select id="categoryFilter"><option value="">All categories</option>${["Farm Equipment","Household","Vehicles","Tools & Shop","Antiques","Miscellaneous"].map(c=>`<option>${c}</option>`).join("")}</select></div></div><div id="inventoryGrid" class="inventory-grid"></div></section><aside class="panel side-panel"><h2>Auction activity</h2><div class="activity"><div class="activity-item"><span class="activity-icon">▦</span><div><strong>${items.length} lots cataloged</strong><small>${ready} ready for review</small></div></div><div class="activity-item"><span class="activity-icon">◎</span><div><strong>${esc(a.status)}</strong><small>Current auction status</small></div></div><div class="activity-item"><span class="activity-icon">#</span><div><strong>Lot ${a.nextLot} next</strong><small>Numbered automatically</small></div></div></div></aside></div>`;renderItems(items);$("#itemSearch").addEventListener("input",filterItems);$("#categoryFilter").addEventListener("change",filterItems)}
function renderItems(items){const grid=$("#inventoryGrid");if(!items.length){grid.innerHTML=`<div class="empty-state"><strong>No items yet</strong>Take photos of the first item to begin this catalog.</div>`;return}grid.innerHTML=items.slice().sort((a,b)=>b.lot-a.lot).map(i=>`<article class="lot-card" data-item="${i.id}" tabindex="0"><div class="lot-image"><img src="${i.photos?.[0]||""}" alt=""><span class="photo-count">▧ ${i.photos?.length||0}</span></div><div class="lot-body"><div class="lot-meta"><span>Lot ${i.lot}</span><span>${esc(i.category)}</span></div><h3>${esc(i.title)}</h3><footer class="lot-foot"><span class="badge">${esc(i.status||"Draft")}</span><span class="price">${money(i.startingBid)}</span></footer></div></article>`).join("")}
function filterItems(){const a=currentAuction(),q=$("#itemSearch").value.toLowerCase(),c=$("#categoryFilter").value;renderItems(a.items.filter(i=>(!c||i.category===c)&&(!q||`${i.title} ${i.lot} ${i.category}`.toLowerCase().includes(q))))}
function renderAuctions(){$("#mainContent").innerHTML=`<header class="page-head"><div><p class="eyebrow">Auction management</p><h1>Your auctions</h1><p class="muted">Create a sale or reopen a catalog already in progress.</p></div><button class="btn primary" data-action="new-auction">＋ New auction</button></header><div class="auction-grid">${state.auctions.map(a=>`<article class="auction-card ${a.id===state.selectedAuctionId?"current":""}"><span class="auction-type">${esc(a.type)}</span><h3>${esc(a.name)}</h3><p class="muted">${fmtDate(a.date)} · ${esc(a.location||"Location not set")}</p><div class="lot-meta"><span>${a.items.length} lots</span><span>${esc(a.status)}</span></div><footer><button class="btn ${a.id===state.selectedAuctionId?"secondary":"dark"}" data-select-auction="${a.id}">${a.id===state.selectedAuctionId?"Current":"Open auction"}</button></footer></article>`).join("")}<button class="setup-card" data-action="new-auction"><div><strong>＋</strong><h2>Create another auction</h2><p>Estate sale, farm, vehicle, or mixed inventory.</p></div></button></div>`}

function openAuctionDialog(){const d=new Date(Date.now()+14*864e5);$("#auctionDate").value=d.toISOString().slice(0,10);$("#auctionDialog").showModal()}
async function createAuction(e){e.preventDefault();const a={id:uid(),name:$("#auctionName").value.trim(),type:$("#auctionType").value,date:$("#auctionDate").value,location:$("#auctionLocation").value.trim(),status:$("#auctionStatus").value,nextLot:Number($("#auctionFirstLot").value)||1,items:[]};state.auctions.push(a);state.selectedAuctionId=a.id;await saveState();$("#auctionDialog").close();e.target.reset();route="dashboard";render();showToast("Auction created")}
function openItem(){const a=currentAuction();if(!a)return;draftPhotos=[];$("#itemForm").reset();$("#lotNumber").value=a.nextLot;$("#itemCategory").value=a.type==="Vehicle"?"Vehicles":a.type==="Farm"?"Farm Equipment":"Household";$("#photoError").classList.add("hidden");showPhotoStep();renderPhotoGrid();toggleVehicle();$("#itemDialog").showModal()}
function showPhotoStep(){$("#photoStep").classList.remove("hidden");$("#detailsStep").classList.add("hidden");$("#backItemBtn").classList.add("hidden");$("#saveItemBtn").classList.add("hidden");$("#continueBtn").classList.remove("hidden");$("#itemStepLabel").textContent="Step 1 of 2 · Photos and recognition"}
function showDetailsStep(){$("#photoStep").classList.add("hidden");$("#detailsStep").classList.remove("hidden");$("#backItemBtn").classList.remove("hidden");$("#saveItemBtn").classList.remove("hidden");$("#continueBtn").classList.add("hidden");$("#itemStepLabel").textContent="Step 2 of 2 · Review and save";toggleVehicle()}
function renderPhotoGrid(){$("#photoGrid").innerHTML=draftPhotos.length?draftPhotos.map((p,n)=>`<div class="photo-tile"><img src="${p}" alt="Item photo ${n+1}"><button type="button" data-remove-photo="${n}" aria-label="Remove photo">×</button></div>`).join(""):`<div class="photo-placeholder"><div><strong>Photograph every useful angle</strong><br><span>Front, back, labels, damage, serial numbers, and VIN plates</span></div></div>`}
async function addFiles(files){const remaining=8-draftPhotos.length;if(!remaining)return showToast("Eight photos is the limit for one item");for(const file of [...files].slice(0,remaining)){try{draftPhotos.push(await compressImage(file))}catch{showToast(`Could not read ${file.name}`)}}renderPhotoGrid();$("#cameraInput").value="";$("#libraryInput").value=""}
async function compressImage(file){let bitmap;try{bitmap=await createImageBitmap(file)}catch{bitmap=await new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject()};img.src=url})}const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return await new Promise((resolve,reject)=>canvas.toBlob(b=>{if(!b)return reject();const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(b)},"image/jpeg",.82))}
async function runAI(engine){if(!draftPhotos.length)return showPhotoError("Add at least one photo before using HammerList AI.");setBusy(true,"HammerList is reviewing the photos…");showPhotoError("");try{const a=currentAuction(),res=await fetch("/api/recognize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({images:draftPhotos.slice(0,3),engine,auctionType:a.type})}),data=await res.json();if(!res.ok)throw new Error(data.error||"The scan could not be completed.");applyAI(data);showDetailsStep();showToast(engine==="secondary"?"Second opinion ready":"Listing suggestion ready")}catch(e){showPhotoError(e.message)}finally{setBusy(false)}}
function applyAI(d){$("#detectedName").textContent=d.detectedName||"Item recognized";$("#confidenceBadge").textContent=`${d.confidence||0}% confidence`;$("#itemTitle").value=d.title||"";$("#itemCategory").value=d.category||"Miscellaneous";$("#itemCondition").value=d.condition||"Unknown";$("#startingBid").value=d.startingBid??"";$("#itemDescription").value=d.description||"";if(d.vin)$("#vinInput").value=d.vin;if(d.vehicleYear)$("#vehicleYear").value=d.vehicleYear;if(d.vehicleMake)$("#vehicleMake").value=d.vehicleMake;if(d.vehicleModel)$("#vehicleModel").value=d.vehicleModel;if(d.vehicleTrim)$("#vehicleTrim").value=d.vehicleTrim;if(d.bodyClass)$("#vehicleBody").value=d.bodyClass;toggleVehicle()}
function showPhotoError(msg){const e=$("#photoError");e.textContent=msg;e.classList.toggle("hidden",!msg)}
function toggleVehicle(){const show=$("#itemCategory").value==="Vehicles"||currentAuction()?.type==="Vehicle";$("#vehicleFields").classList.toggle("hidden",!show)}
function cleanVin(){return $("#vinInput").value.toUpperCase().replace(/[^A-HJ-NPR-Z0-9]/g,"").slice(0,17)}
async function decodeVin(){const vin=cleanVin();$("#vinInput").value=vin;if(vin.length!==17){$("#vinMessage").textContent="Enter a complete 17-character VIN.";return}setBusy(true,"Looking up the VIN…");try{const res=await fetch(`/api/vin?vin=${encodeURIComponent(vin)}`),d=await res.json();if(!res.ok)throw new Error(d.error||"VIN lookup failed");$("#vehicleYear").value=d.year||"";$("#vehicleMake").value=d.make||"";$("#vehicleModel").value=d.model||"";$("#vehicleTrim").value=d.trim||"";$("#vehicleBody").value=d.body||"";$("#vehicleEngine").value=d.engine||"";$("#vehicleDrive").value=d.drive||"";if(!$("#itemTitle").value)$("#itemTitle").value=[d.year,d.make,d.model,d.trim].filter(Boolean).join(" ");$("#vinMessage").textContent="Vehicle details loaded from NHTSA. Confirm them against the vehicle before publishing.";showToast("VIN decoded")}catch(e){$("#vinMessage").textContent=e.message}finally{setBusy(false)}}
async function scanVin(){if(!draftPhotos.length){$("#vinMessage").textContent="Add a clear photo of the VIN plate first.";return}setBusy(true,"Reading the VIN from your photos…");try{const res=await fetch("/api/vin-scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({images:draftPhotos.slice(0,3)})}),d=await res.json();if(!res.ok)throw new Error(d.error||"VIN could not be read");if(!d.vin)throw new Error("No complete VIN was visible. Take a closer, well-lit photo of the VIN plate.");$("#vinInput").value=d.vin;await decodeVin()}catch(e){$("#vinMessage").textContent=e.message}finally{setBusy(false)}}
async function saveItem(e){e.preventDefault();if(!draftPhotos.length)return showToast("Add at least one photo");const a=currentAuction(),vehicle=$("#itemCategory").value==="Vehicles",item={id:uid(),lot:Number($("#lotNumber").value),title:$("#itemTitle").value.trim(),category:$("#itemCategory").value,condition:$("#itemCondition").value,startingBid:Number($("#startingBid").value)||0,description:$("#itemDescription").value.trim(),confidence:Number($("#confidenceBadge").textContent.match(/\d+/)?.[0]||0),status:"Ready",photos:[...draftPhotos],createdAt:new Date().toISOString()};if(vehicle)Object.assign(item,{vin:cleanVin(),year:$("#vehicleYear").value,make:$("#vehicleMake").value,model:$("#vehicleModel").value,trim:$("#vehicleTrim").value,body:$("#vehicleBody").value,engine:$("#vehicleEngine").value,drive:$("#vehicleDrive").value,mileage:$("#vehicleMileage").value});a.items.push(item);a.nextLot=Math.max(a.nextLot,item.lot+1);await saveState();$("#itemDialog").close();render();showToast(`Lot ${item.lot} saved with ${item.photos.length} photo${item.photos.length===1?"":"s"}`)}
function viewItem(id){const a=currentAuction(),i=a.items.find(x=>x.id===id);if(!i)return;const vehicle=i.category==="Vehicles";$("#itemViewContent").innerHTML=`<header class="dialog-head"><div><p class="eyebrow">Lot ${i.lot} · ${esc(i.category)}</p><h2>${esc(i.title)}</h2></div><button type="button" class="icon-btn" data-close="itemViewDialog">×</button></header><div class="item-view-gallery">${i.photos.map((p,n)=>`<img src="${p}" alt="${esc(i.title)} photo ${n+1}">`).join("")}</div><div class="item-view-details"><div class="detail-table"><div class="detail-cell"><small>Condition</small><strong>${esc(i.condition)}</strong></div><div class="detail-cell"><small>Starting bid</small><strong>${money(i.startingBid)}</strong></div><div class="detail-cell"><small>Status</small><strong>${esc(i.status)}</strong></div>${vehicle?`<div class="detail-cell"><small>VIN</small><strong>${esc(i.vin||"Not entered")}</strong></div><div class="detail-cell"><small>Vehicle</small><strong>${esc([i.year,i.make,i.model].filter(Boolean).join(" ")||"Not decoded")}</strong></div><div class="detail-cell"><small>Mileage</small><strong>${i.mileage?Number(i.mileage).toLocaleString():"Not entered"}</strong></div>`:""}</div><p>${esc(i.description)}</p><button class="btn secondary" data-delete-item="${i.id}">Delete demo item</button></div>`;$("#itemViewDialog").showModal()}
async function deleteItem(id){if(!confirm("Delete this item from the demo catalog?"))return;const a=currentAuction();a.items=a.items.filter(i=>i.id!==id);await saveState();$("#itemViewDialog").close();render();showToast("Item deleted")}

$("#loginForm").addEventListener("submit",e=>{e.preventDefault();if($("#loginEmail").value.toLowerCase()!=="auctioneer@hammerlist.app"||$("#loginPassword").value!=="demo123")return showToast("Use the demo credentials shown below the form");sessionStorage.setItem("hammerlist-session",$("#loginEmail").value);startApp()});
function startApp(){$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#signedInEmail").textContent=sessionStorage.getItem("hammerlist-session")||"auctioneer@hammerlist.app";render()}
function logout(){sessionStorage.removeItem("hammerlist-session");$("#appView").classList.add("hidden");$("#loginView").classList.remove("hidden")}
$("#logoutBtn").onclick=logout;$("#profileBtn").onclick=logout;$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");$("#auctionSelect").onchange=async e=>{state.selectedAuctionId=e.target.value;await saveState();render()};
$$('.nav-item').forEach(b=>b.onclick=()=>{route=b.dataset.route;$("#sidebar").classList.remove("open");render()});
document.addEventListener("click",async e=>{const action=e.target.closest("[data-action]")?.dataset.action;if(action==="new-auction")openAuctionDialog();if(action==="add-item")openItem();if(action==="auctions"){route="auctions";render()}const auctionId=e.target.closest("[data-select-auction]")?.dataset.selectAuction;if(auctionId){state.selectedAuctionId=auctionId;route="dashboard";await saveState();render()}const itemId=e.target.closest("[data-item]")?.dataset.item;if(itemId)viewItem(itemId);const remove=e.target.closest("[data-remove-photo]")?.dataset.removePhoto;if(remove!==undefined){draftPhotos.splice(Number(remove),1);renderPhotoGrid()}const del=e.target.closest("[data-delete-item]")?.dataset.deleteItem;if(del)deleteItem(del);const close=e.target.closest("[data-close]")?.dataset.close;if(close)$("#"+close).close()});
$("#auctionForm").addEventListener("submit",createAuction);$("#cameraInput").onchange=e=>addFiles(e.target.files);$("#libraryInput").onchange=e=>addFiles(e.target.files);$("#scanBtn").onclick=()=>runAI("primary");$("#secondOpinionBtn").onclick=()=>runAI("secondary");$("#continueBtn").onclick=showDetailsStep;$("#backItemBtn").onclick=showPhotoStep;$("#closeItem").onclick=()=>$("#itemDialog").close();$("#itemCategory").onchange=toggleVehicle;$("#decodeVinBtn").onclick=decodeVin;$("#scanVinBtn").onclick=scanVin;$("#itemForm").addEventListener("submit",saveItem);$("#mobileAdd").onclick=openItem;
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}));
await loadState();if(sessionStorage.getItem("hammerlist-session"))startApp();
