import { Capacitor } from "@capacitor/core";
import { Camera, CameraResultType, CameraSource } from "@capacitor/camera";
import { Directory, Filesystem } from "@capacitor/filesystem";
import { Share } from "@capacitor/share";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const uid=()=>typeof crypto!=="undefined"&&typeof crypto.randomUUID==="function"?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const seed={selectedAuctionId:"auction-1",auctions:[{id:"auction-1",name:"Johnson Farm & Estate Auction",type:"Mixed",date:"2026-10-10",location:"Lexington, Tennessee",status:"Cataloging",nextLot:129,items:[
{id:"lot-126",lot:126,title:"1937 John Deere AR Tractor",category:"Farm Equipment",condition:"Good used condition",startingBid:2500,description:"Two-cylinder row-crop tractor. Verify serial number, operating condition, and restoration history before publishing.",confidence:94,status:"Ready",photos:["assets/tractor.jpg"],createdAt:"2026-09-18T10:00:00Z"},
{id:"lot-127",lot:127,title:"Hand-carved French Oak Cabinet",category:"Antiques",condition:"Good used condition",startingBid:325,description:"Tall carved oak display cabinet with glazed door and fitted shelves. Inspect hardware and finish for age-related wear.",confidence:88,status:"Ready",photos:["assets/cabinet.jpg"],createdAt:"2026-09-18T10:10:00Z"},
{id:"lot-128",lot:128,title:"1972 Ford F-250 Pickup",category:"Vehicles",condition:"Fair",startingBid:1800,description:"Vintage Ford pickup. Verify VIN, mileage, title status, engine, and running condition before publishing.",confidence:91,status:"Ready",photos:["assets/truck.jpg"],vin:"",year:"1972",make:"Ford",model:"F-250",trim:"",body:"Pickup",engine:"",drive:"",mileage:"",createdAt:"2026-09-18T10:20:00Z"}]}]};
let state=null,route="dashboard",draftPhotos=[],vinPhoto="",working=false,visionModelPromise=null;
const isNative=Capacitor.isNativePlatform();
const apiBase=String(globalThis.HAMMERLIST_API_BASE_URL||"").replace(/\/+$/,"");
const apiUrl=path=>apiBase?`${apiBase}${path}`:`.${path}`;

function nativeCancelled(error){return /cancel|user cancelled|user canceled/i.test(String(error?.message||error||""))}
async function nativePhotoFile(photo,prefix="photo"){
  if(!photo?.webPath)throw new Error("The selected photo could not be opened.");
  const response=await fetch(photo.webPath),blob=await response.blob();
  if(!response.ok)throw new Error("The selected photo could not be opened.");
  return new File([blob],`${prefix}-${Date.now()}.${photo.format||"jpeg"}`,{type:blob.type||`image/${photo.format||"jpeg"}`});
}
async function takeNativeItemPhoto(){if(working)return;try{const photo=await Camera.getPhoto({source:CameraSource.Camera,resultType:CameraResultType.Uri,quality:88,width:1800,correctOrientation:true,saveToGallery:false});await addFiles([await nativePhotoFile(photo,"item")])}catch(error){if(!nativeCancelled(error))showToast(error.message||"The camera could not be opened.")}}
async function chooseNativeItemPhotos(){if(working)return;const remaining=8-draftPhotos.length;if(!remaining)return showToast("Eight photos is the limit for one item");try{const result=await Camera.pickImages({quality:88,width:1800,correctOrientation:true,limit:remaining});const files=[];for(const photo of result.photos||[])files.push(await nativePhotoFile(photo,"item"));await addFiles(files)}catch(error){if(!nativeCancelled(error))showToast(error.message||"The photo library could not be opened.")}}
async function takeNativeVinPhoto(){if(working)return;try{const photo=await Camera.getPhoto({source:CameraSource.Camera,resultType:CameraResultType.Uri,quality:94,width:2200,correctOrientation:true,saveToGallery:false});await scanVinCamera([await nativePhotoFile(photo,"vin")])}catch(error){if(!nativeCancelled(error))$("#vinMessage").textContent=error.message||"The camera could not be opened."}}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.onerror=reject;reader.readAsDataURL(blob)})}

function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open("hammerlist-demo",1);r.onupgradeneeded=()=>r.result.createObjectStore("app");r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
const freshSeed=()=>typeof structuredClone==="function"?structuredClone(seed):JSON.parse(JSON.stringify(seed));
async function loadState(){try{const d=await db();state=await new Promise((resolve,reject)=>{const t=d.transaction("app","readonly").objectStore("app").get("state");t.onsuccess=()=>resolve(t.result);t.onerror=()=>reject(t.error)});d.close()}catch{}if(!state)state=freshSeed()}
async function saveState(){try{const d=await db();await new Promise((resolve,reject)=>{const t=d.transaction("app","readwrite").objectStore("app").put(state,"state");t.onsuccess=resolve;t.onerror=()=>reject(t.error)});d.close()}catch(e){showToast("Could not save on this device. Check available storage.")}}
function currentAuction(){return state.auctions.find(a=>a.id===state.selectedAuctionId)||null}
function showToast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove("show"),2800)}
function fmtDate(v){if(!v)return"Date not set";return new Date(`${v}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}
function money(v){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(v)||0)}
function setBusy(value,label="Working…"){working=value;[$("#scanBtn"),$("#secondOpinionBtn"),$("#scanVinBtn"),$("#decodeVinBtn"),$("#vinCameraInput")].filter(Boolean).forEach(b=>{b.disabled=value});if(value)showToast(label)}

function render(){const auction=currentAuction();$("#auctionSelect").innerHTML=state.auctions.length?state.auctions.map(a=>`<option value="${a.id}" ${a.id===state.selectedAuctionId?"selected":""}>${esc(a.name)}</option>`).join(""):`<option>No auctions yet</option>`;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));$("#mobileAdd").classList.toggle("hidden",!auction||route==="auctions");if(route==="auctions")renderAuctions();else if(!auction)renderNoAuction();else renderWorkspace(auction,route==="inventory")}
function renderNoAuction(){$("#mainContent").innerHTML=`<section class="setup-card"><div><p class="eyebrow">Get started</p><h2>Create your first auction</h2><p>Name the sale, choose its type, and HammerList will prepare the right catalog fields.</p><button class="btn primary" data-action="new-auction">Create auction</button></div></section>`}
function workflow(a){const total=a.items.length;const ready=a.items.filter(i=>i.status==="Ready").length;return`<div class="workflow-strip"><div class="workflow-step active"><strong>1</strong><span>Auction created</span></div><div class="workflow-step ${total?"active":""}"><strong>2</strong><span>Catalog items</span></div><div class="workflow-step ${ready&&ready===total?"active":""}"><strong>3</strong><span>Review lots</span></div><div class="workflow-step ${a.status==="Ready"?"active":""}"><strong>4</strong><span>Publish ready</span></div></div>`}
function renderWorkspace(a,inventoryOnly=false){const items=a.items||[],ready=items.filter(i=>i.status==="Ready").length,categories=new Set(items.map(i=>i.category)).size;$("#mainContent").innerHTML=`<header class="page-head"><div><p class="eyebrow">${esc(a.type)} auction</p><h1>${inventoryOnly?"Inventory":esc(a.name)}</h1><p class="muted">${inventoryOnly?esc(a.name):`${fmtDate(a.date)} · ${esc(a.location)}`}</p></div><div class="header-actions"><button class="btn secondary" data-action="auctions">Switch auction</button><button class="btn secondary" data-action="export">Export / publish</button><button class="btn primary" data-action="add-item">＋ Add item</button></div></header>${inventoryOnly?"":workflow(a)}<div class="stats"><div class="stat"><small>Total lots</small><strong>${items.length}</strong></div><div class="stat"><small>Ready</small><strong>${ready}</strong></div><div class="stat"><small>Categories</small><strong>${categories}</strong></div><div class="stat"><small>Next lot</small><strong>#${a.nextLot}</strong></div></div><div class="content-grid"><section class="panel"><div class="panel-head"><h2>${inventoryOnly?"All inventory":"Recent inventory"}</h2><div class="filters"><input id="itemSearch" placeholder="Search lots"><select id="categoryFilter"><option value="">All categories</option>${["Farm Equipment","Household","Vehicles","Tools & Shop","Antiques","Miscellaneous"].map(c=>`<option>${c}</option>`).join("")}</select></div></div><div id="inventoryGrid" class="inventory-grid"></div></section><aside class="panel side-panel"><h2>Auction activity</h2><div class="activity"><div class="activity-item"><span class="activity-icon">▦</span><div><strong>${items.length} lots cataloged</strong><small>${ready} ready for review</small></div></div><div class="activity-item"><span class="activity-icon">◎</span><div><strong>${esc(a.status)}</strong><small>Current auction status</small></div></div><div class="activity-item"><span class="activity-icon">#</span><div><strong>Lot ${a.nextLot} next</strong><small>Numbered automatically</small></div></div></div></aside></div>`;renderItems(items);$("#itemSearch").addEventListener("input",filterItems);$("#categoryFilter").addEventListener("change",filterItems)}
function renderItems(items){const grid=$("#inventoryGrid");if(!items.length){grid.innerHTML=`<div class="empty-state"><strong>No items yet</strong>Take photos of the first item to begin this catalog.</div>`;return}grid.innerHTML=items.slice().sort((a,b)=>b.lot-a.lot).map(i=>`<article class="lot-card" data-item="${i.id}" tabindex="0"><div class="lot-image"><img src="${i.photos?.[0]||""}" alt=""><span class="photo-count">▧ ${i.photos?.length||0}</span></div><div class="lot-body"><div class="lot-meta"><span>Lot ${i.lot}</span><span>${esc(i.category)}</span></div><h3>${esc(i.title)}</h3><footer class="lot-foot"><span class="badge">${esc(i.status||"Draft")}</span><span class="price">${money(i.startingBid)}</span></footer></div></article>`).join("")}
function filterItems(){const a=currentAuction(),q=$("#itemSearch").value.toLowerCase(),c=$("#categoryFilter").value;renderItems(a.items.filter(i=>(!c||i.category===c)&&(!q||`${i.title} ${i.lot} ${i.category}`.toLowerCase().includes(q))))}
function renderAuctions(){$("#mainContent").innerHTML=`<header class="page-head"><div><p class="eyebrow">Auction management</p><h1>Your auctions</h1><p class="muted">Create a sale or reopen a catalog already in progress.</p></div><button class="btn primary" data-action="new-auction">＋ New auction</button></header><div class="auction-grid">${state.auctions.map(a=>`<article class="auction-card ${a.id===state.selectedAuctionId?"current":""}"><span class="auction-type">${esc(a.type)}</span><h3>${esc(a.name)}</h3><p class="muted">${fmtDate(a.date)} · ${esc(a.location||"Location not set")}</p><div class="lot-meta"><span>${a.items.length} lots</span><span>${esc(a.status)}</span></div><footer><button class="btn ${a.id===state.selectedAuctionId?"secondary":"dark"}" data-select-auction="${a.id}">${a.id===state.selectedAuctionId?"Current":"Open auction"}</button></footer></article>`).join("")}<button class="setup-card" data-action="new-auction"><div><strong>＋</strong><h2>Create another auction</h2><p>Estate sale, farm, vehicle, or mixed inventory.</p></div></button></div>`}

function openAuctionDialog(){const d=new Date(Date.now()+14*864e5);$("#auctionDate").value=d.toISOString().slice(0,10);$("#auctionDialog").showModal()}
async function createAuction(e){e.preventDefault();const a={id:uid(),name:$("#auctionName").value.trim(),type:$("#auctionType").value,date:$("#auctionDate").value,location:$("#auctionLocation").value.trim(),status:$("#auctionStatus").value,nextLot:Number($("#auctionFirstLot").value)||1,items:[]};state.auctions.push(a);state.selectedAuctionId=a.id;await saveState();$("#auctionDialog").close();e.target.reset();route="dashboard";render();showToast("Auction created")}
function itemKind(){return document.querySelector('input[name="itemKind"]:checked')?.value||"estate"}
function setItemKind(kind){const radio=document.querySelector(`input[name="itemKind"][value="${kind}"]`);if(radio)radio.checked=true;if(kind==="vehicle")$("#itemCategory").value="Vehicles";else if(kind==="farm")$("#itemCategory").value="Farm Equipment";else if(["Vehicles","Farm Equipment"].includes($("#itemCategory").value))$("#itemCategory").value="Household";$("#vehicleModeHint").classList.toggle("hidden",kind!=="vehicle");$("#farmModeHint").classList.toggle("hidden",kind!=="farm");$("#continueBtn").textContent=kind==="vehicle"?"Continue to vehicle & VIN":kind==="farm"?"Continue to farm equipment details":"Continue to item details";toggleVehicle()}
function openItem(){const a=currentAuction();if(!a)return;draftPhotos=[];vinPhoto="";$("#itemForm").reset();$("#lotNumber").value=a.nextLot;$("#itemCategory").value=a.type==="Vehicle"?"Vehicles":a.type==="Farm"?"Farm Equipment":"Household";setItemKind(a.type==="Vehicle"?"vehicle":a.type==="Farm"?"farm":"estate");$("#photoError").classList.add("hidden");$("#vinPreview").classList.add("hidden");$("#vinMessage").textContent="Take a close VIN photo or enter the number manually. Successful scans automatically fill the fields below.";showPhotoStep();renderPhotoGrid();$("#itemDialog").showModal()}
function showPhotoStep(){$("#photoStep").classList.remove("hidden");$("#detailsStep").classList.add("hidden");$("#backItemBtn").classList.add("hidden");$("#saveItemBtn").classList.add("hidden");$("#continueBtn").classList.remove("hidden");$("#itemStepLabel").textContent="Step 1 of 2 · Item type and photos";setItemKind(itemKind())}
function showDetailsStep(){$("#photoStep").classList.add("hidden");$("#detailsStep").classList.remove("hidden");$("#backItemBtn").classList.remove("hidden");$("#saveItemBtn").classList.remove("hidden");$("#continueBtn").classList.add("hidden");$("#itemStepLabel").textContent="Step 2 of 2 · Review and save";toggleVehicle()}
function renderPhotoGrid(){$("#photoGrid").innerHTML=draftPhotos.length?draftPhotos.map((p,n)=>`<div class="photo-tile"><img src="${p}" alt="Item photo ${n+1}"><button type="button" data-remove-photo="${n}" aria-label="Remove photo">×</button></div>`).join(""):`<div class="photo-placeholder"><div><strong>Photograph every useful angle</strong><br><span>Front, back, labels, damage, serial numbers, and VIN plates</span></div></div>`}
async function addFiles(files){const remaining=8-draftPhotos.length;if(!remaining)return showToast("Eight photos is the limit for one item");for(const file of [...files].slice(0,remaining)){try{draftPhotos.push(await compressImage(file))}catch{showToast(`Could not read ${file.name}`)}}renderPhotoGrid();$("#cameraInput").value="";$("#libraryInput").value=""}
async function compressImage(file){let bitmap;try{bitmap=await createImageBitmap(file)}catch{bitmap=await new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject()};img.src=url})}const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return await new Promise((resolve,reject)=>canvas.toBlob(b=>{if(!b)return reject();const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(b)},"image/jpeg",.82))}
function demoRecognition(engine){const kind=itemKind();if(kind==="vehicle")return{detectedName:"Vehicle photographed",title:"Vehicle — scan VIN or verify year, make and model",category:"Vehicles",condition:"Unknown",startingBid:500,description:"Vehicle photographed for auction. Scan or enter the VIN, then confirm mileage, title status, operating condition, and visible damage before publishing.",confidence:72};if(kind==="farm")return{detectedName:"Farm equipment photographed",title:"Farm equipment — verify make and model",category:"Farm Equipment",condition:"Good used condition",startingBid:250,description:"Farm equipment photographed for auction. Confirm manufacturer, model, serial number, hours, attachments, and operating condition before publishing.",confidence:74};return{detectedName:engine==="secondary"?"Estate item second review":"Estate item photographed",title:"Estate sale item — review listing title",category:"Household",condition:"Good used condition",startingBid:25,description:"Estate item photographed for auction. Confirm maker, material, dimensions, age, markings, completeness, and visible wear before publishing.",confidence:70}}
function loadScript(src,id){return new Promise((resolve,reject)=>{if(window[id])return resolve();const existing=document.querySelector(`script[data-loader="${id}"]`);if(existing){existing.addEventListener("load",resolve,{once:true});existing.addEventListener("error",reject,{once:true});return}const s=document.createElement("script");s.src=src;s.dataset.loader=id;s.onload=resolve;s.onerror=()=>reject(new Error("Recognition model could not be downloaded."));document.head.appendChild(s)})}
async function getVisionModel(){if(!visionModelPromise)visionModelPromise=(async()=>{await loadScript("https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/dist/tf.min.js","tf");await loadScript("https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@2.1.1/dist/mobilenet.min.js","mobilenet");return mobilenet.load({version:2,alpha:.5})})().catch(e=>{visionModelPromise=null;throw e});return visionModelPromise}
function titleCase(v){return v.replace(/\b\w/g,c=>c.toUpperCase())}
function predictionCategory(label){const l=label.toLowerCase(),kind=itemKind();if(kind==="vehicle")return"Vehicles";if(kind==="farm")return"Farm Equipment";if(/cabinet|wardrobe|table|chair|sofa|couch|desk|bookcase|chest|lamp|refrigerator|washer|stove|microwave|television/.test(l))return"Household";if(/hammer|drill|saw|wrench|screwdriver|plane|vise|tool|chain saw/.test(l))return"Tools & Shop";if(/antique|vase|clock|silver|collectible/.test(l))return"Antiques";return"Miscellaneous"}
async function recognizeOnDevice(){const model=await getVisionModel(),img=new Image();img.src=draftPhotos[0];if(img.decode)await img.decode();else await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject});const predictions=await model.classify(img,5);if(!predictions.length)throw new Error("No recognizable item was found in the photo.");const top=predictions[0],primary=top.className.split(",")[0].trim(),category=predictionCategory(top.className,currentAuction()?.type),alternates=predictions.slice(1,3).map(p=>p.className.split(",")[0].trim()).join(", ");return{detectedName:titleCase(primary),title:titleCase(primary),category,condition:"Unknown",startingBid:category==="Vehicles"?500:category==="Farm Equipment"?250:category==="Tools & Shop"?50:25,description:`Photo recognition suggests ${primary}${alternates?`; other possible matches are ${alternates}`:""}. Confirm the exact maker, model, dimensions, condition, markings, and completeness before publishing.`,confidence:Math.max(1,Math.round(top.probability*100))}}
async function runAI(engine){if(!draftPhotos.length)return showPhotoError("Add at least one photo before using HammerList AI.");setBusy(true,"HammerList is reviewing the photos…");showPhotoError("");try{const a=currentAuction();let data=null,mode="server";try{const res=await fetch(apiUrl("/api/recognize"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({images:draftPhotos.slice(0,3),engine,auctionType:a.type})});if(res.ok)data=await res.json()}catch{}if(!data){mode="device";showToast("Starting on-device recognition — the first scan may take a moment");try{data=await recognizeOnDevice()}catch{mode="demo";data=demoRecognition(engine)}}applyAI(data);showDetailsStep();showToast(mode==="device"?"Photo recognized on this device — review the result":mode==="demo"?"Recognition unavailable — review the editable suggestion":engine==="secondary"?"Second opinion ready":"Listing suggestion ready")}catch(e){showPhotoError(e.message||"The scan could not be completed.")}finally{setBusy(false)}}
function applyAI(d){const kind=itemKind(),category=kind==="vehicle"?"Vehicles":kind==="farm"?"Farm Equipment":["Vehicles","Farm Equipment"].includes(d.category)?"Miscellaneous":d.category||"Miscellaneous";$("#detectedName").textContent=d.detectedName||"Item recognized";$("#confidenceBadge").textContent=`${d.confidence||0}% confidence`;$("#itemTitle").value=d.title||"";$("#itemCategory").value=category;$("#itemCondition").value=d.condition||"Unknown";$("#startingBid").value=d.startingBid??"";$("#itemDescription").value=d.description||"";if(d.vin)$("#vinInput").value=d.vin;if(d.vehicleYear)$("#vehicleYear").value=d.vehicleYear;if(d.vehicleMake)$("#vehicleMake").value=d.vehicleMake;if(d.vehicleModel)$("#vehicleModel").value=d.vehicleModel;if(d.vehicleTrim)$("#vehicleTrim").value=d.vehicleTrim;if(d.bodyClass)$("#vehicleBody").value=d.bodyClass;toggleVehicle()}
function showPhotoError(msg){const e=$("#photoError");e.textContent=msg;e.classList.toggle("hidden",!msg)}
function toggleVehicle(){const show=itemKind()==="vehicle"||$("#itemCategory").value==="Vehicles";$("#vehicleFields").classList.toggle("hidden",!show)}
function cleanVin(){return $("#vinInput").value.toUpperCase().replace(/[^A-HJ-NPR-Z0-9]/g,"").slice(0,17)}
async function decodeVin(){const vin=cleanVin();$("#vinInput").value=vin;if(vin.length!==17){$("#vinMessage").textContent="Enter a complete 17-character VIN.";return}setBusy(true,"Looking up the VIN…");try{const res=await fetch(`https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValuesExtended/${encodeURIComponent(vin)}?format=json`),payload=await res.json(),v=payload.Results?.[0]||{};if(!res.ok||!payload.Results?.length)throw new Error("VIN lookup failed");if(v.ErrorCode&&String(v.ErrorCode).split(",").some(code=>code.trim()!=="0"))throw new Error(v.ErrorText||"The VIN could not be validated.");const d={year:v.ModelYear,make:v.Make,model:v.Model,trim:v.Trim,body:v.BodyClass,engine:[v.DisplacementL&&`${v.DisplacementL}L`,v.EngineCylinders&&`${v.EngineCylinders} cyl`,v.FuelTypePrimary].filter(Boolean).join(" "),drive:v.DriveType};$("#vehicleYear").value=d.year||"";$("#vehicleMake").value=d.make||"";$("#vehicleModel").value=d.model||"";$("#vehicleTrim").value=d.trim||"";$("#vehicleBody").value=d.body||"";$("#vehicleEngine").value=d.engine||"";$("#vehicleDrive").value=d.drive||"";$("#itemTitle").value=[d.year,d.make,d.model,d.trim].filter(Boolean).join(" ")||$("#itemTitle").value;$("#vinMessage").textContent="Vehicle details loaded from NHTSA. Confirm them against the vehicle before publishing.";showToast("VIN decoded and vehicle fields populated")}catch(e){$("#vinMessage").textContent=e.message||"VIN lookup failed"}finally{setBusy(false)}}
function extractVin(text){const lines=String(text||"").toUpperCase().split(/\n+/);for(const line of lines){const normalized=line.replace(/[OQ]/g,"0").replace(/I/g,"1").replace(/[^A-HJ-NPR-Z0-9]/g,"");const match=normalized.match(/[A-HJ-NPR-Z0-9]{17}/);if(match)return match[0]}return""}
async function readVinOnDevice(images=draftPhotos.slice(0,3)){await loadScript("https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js","Tesseract");const worker=await Tesseract.createWorker("eng");await worker.setParameters({tessedit_char_whitelist:"ABCDEFGHJKLMNPRSTUVWXYZ0123456789",tessedit_pageseg_mode:"6",preserve_interword_spaces:"0"});try{for(const photo of images){const result=await worker.recognize(photo),vin=extractVin(result.data?.text);if(vin)return vin}}finally{await worker.terminate()}return""}
async function recognizeAndDecodeVin(images){setBusy(true,"Reading the VIN…");$("#vinMessage").textContent="Reading the 17-character VIN. The first scan may take a moment.";try{let vin="";try{const res=await fetch(apiUrl("/api/vin-scan"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({images:images.slice(0,3)})});if(res.ok)vin=(await res.json()).vin||""}catch{}if(!vin)vin=await readVinOnDevice(images);if(!vin)throw new Error("No complete VIN was visible. Move closer, hold the phone straight, and avoid glare.");$("#vinInput").value=vin;await decodeVin()}catch(e){$("#vinMessage").textContent=e.message||"VIN could not be read"}finally{setBusy(false)}}
async function scanVin(){if(!draftPhotos.length){$("#vinMessage").textContent="Add a clear VIN plate photo or use Open camera & scan VIN.";return}await recognizeAndDecodeVin(draftPhotos)}
async function scanVinCamera(files){const file=files?.[0];if(!file)return;try{vinPhoto=await compressImage(file);$("#vinPreviewImage").src=vinPhoto;$("#vinPreview").classList.remove("hidden");if(draftPhotos.length<8){draftPhotos.push(vinPhoto);renderPhotoGrid()}await recognizeAndDecodeVin([vinPhoto])}catch(e){$("#vinMessage").textContent=e.message||"The VIN photo could not be read."}finally{$("#vinCameraInput").value=""}}
async function saveItem(e){e.preventDefault();if(!draftPhotos.length)return showToast("Add at least one photo");const a=currentAuction(),vehicle=itemKind()==="vehicle"||$("#itemCategory").value==="Vehicles",item={id:uid(),lot:Number($("#lotNumber").value),title:$("#itemTitle").value.trim(),category:vehicle?"Vehicles":$("#itemCategory").value,condition:$("#itemCondition").value,startingBid:Number($("#startingBid").value)||0,description:$("#itemDescription").value.trim(),confidence:Number($("#confidenceBadge").textContent.match(/\d+/)?.[0]||0),status:"Ready",photos:[...draftPhotos],createdAt:new Date().toISOString()};if(vehicle)Object.assign(item,{vin:cleanVin(),year:$("#vehicleYear").value,make:$("#vehicleMake").value,model:$("#vehicleModel").value,trim:$("#vehicleTrim").value,body:$("#vehicleBody").value,engine:$("#vehicleEngine").value,drive:$("#vehicleDrive").value,mileage:$("#vehicleMileage").value});a.items.push(item);a.nextLot=Math.max(a.nextLot,item.lot+1);await saveState();$("#itemDialog").close();render();showToast(`Lot ${item.lot} saved with ${item.photos.length} photo${item.photos.length===1?"":"s"}`)}
function viewItem(id){const a=currentAuction(),i=a.items.find(x=>x.id===id);if(!i)return;const vehicle=i.category==="Vehicles";$("#itemViewContent").innerHTML=`<header class="dialog-head"><div><p class="eyebrow">Lot ${i.lot} · ${esc(i.category)}</p><h2>${esc(i.title)}</h2></div><button type="button" class="icon-btn" data-close="itemViewDialog">×</button></header><div class="item-view-gallery">${i.photos.map((p,n)=>`<img src="${p}" alt="${esc(i.title)} photo ${n+1}">`).join("")}</div><div class="item-view-details"><div class="detail-table"><div class="detail-cell"><small>Condition</small><strong>${esc(i.condition)}</strong></div><div class="detail-cell"><small>Starting bid</small><strong>${money(i.startingBid)}</strong></div><div class="detail-cell"><small>Status</small><strong>${esc(i.status)}</strong></div>${vehicle?`<div class="detail-cell"><small>VIN</small><strong>${esc(i.vin||"Not entered")}</strong></div><div class="detail-cell"><small>Vehicle</small><strong>${esc([i.year,i.make,i.model].filter(Boolean).join(" ")||"Not decoded")}</strong></div><div class="detail-cell"><small>Mileage</small><strong>${i.mileage?Number(i.mileage).toLocaleString():"Not entered"}</strong></div>`:""}</div><p>${esc(i.description)}</p><button class="btn secondary" data-delete-item="${i.id}">Delete demo item</button></div>`;$("#itemViewDialog").showModal()}
async function deleteItem(id){if(!confirm("Delete this item from the demo catalog?"))return;const a=currentAuction();a.items=a.items.filter(i=>i.id!==id);await saveState();$("#itemViewDialog").close();render();showToast("Item deleted")}

function csvCell(value){const text=String(value??"");return /[",\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
function csv(rows){return "\ufeff"+rows.map(row=>row.map(csvCell).join(",")).join("\r\n")}
function safeName(value){return String(value||"auction").trim().replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"auction"}
function photoNames(item){return (item.photos||[]).map((_,index)=>`${item.lot}-${index+1}.jpg`)}
function exportIssues(auction){const issues=[];if(!auction.items.length)issues.push("Add at least one lot");auction.items.forEach(item=>{if(!item.title)issues.push(`Lot ${item.lot}: missing title`);if(!item.description)issues.push(`Lot ${item.lot}: missing description`);if(!item.photos?.length)issues.push(`Lot ${item.lot}: missing photo`);if(item.category==="Vehicles"&&!item.vin)issues.push(`Lot ${item.lot}: VIN not entered`)});return issues}
function platformCatalog(platform,auction){const common=item=>({lot:item.lot,title:item.title,description:item.description,category:item.category,condition:item.condition,startingBid:item.startingBid,quantity:1,images:photoNames(item).join("|"),vin:item.vin||"",year:item.year||"",make:item.make||"",model:item.model||"",trim:item.trim||"",mileage:item.mileage||""});const values=auction.items.slice().sort((a,b)=>a.lot-b.lot).map(common);if(platform==="auctionflex")return[["Consignor Code","Inventory Number","Lot Number","Lead","Description","Quantity","Reserve","Low Estimate","High Estimate","Category","Condition","Starting Bid","Image Filenames","VIN","Year","Make","Model","Trim","Mileage"],...values.map(v=>["HOUSE",v.lot,v.lot,v.title,v.description,v.quantity,"","","",v.category,v.condition,v.startingBid,v.images,v.vin,v.year,v.make,v.model,v.trim,v.mileage])];if(platform==="proxibid")return[["Lot Number","Title","Description","Category","Quantity","Starting Bid","Reserve","Condition","Image Files","VIN","Year","Make","Model","Mileage"],...values.map(v=>[v.lot,v.title,v.description,v.category,v.quantity,v.startingBid,"",v.condition,v.images,v.vin,v.year,v.make,v.model,v.mileage])];if(platform==="ebay")return[["SKU","Title","Description","Condition","Quantity","Price","Category","Image Files","VIN","Year","Make","Model","Mileage"],...values.map(v=>[`LOT-${v.lot}`,v.title,v.description,v.condition,v.quantity,v.startingBid,v.category,v.images,v.vin,v.year,v.make,v.model,v.mileage])];return[["Lot Number","Title","Description","Category","Condition","Starting Bid","Quantity","Image Files","VIN","Year","Make","Model","Trim","Mileage"],...values.map(v=>[v.lot,v.title,v.description,v.category,v.condition,v.startingBid,v.quantity,v.images,v.vin,v.year,v.make,v.model,v.trim,v.mileage])]}
function exportSettings(){return{destination:$("#exportPlatform").value,biddingType:$("#exportBiddingType").value,buyersPremiumPercent:Number($("#exportPremium").value)||0,lotStaggerSeconds:Number($("#exportStagger").value)||0,softCloseMinutes:Number($("#exportSoftClose").value)||0,pickupShipping:$("#exportPickup").value.trim(),terms:$("#exportTerms").value.trim()}}
function renderExportSummary(){const a=currentAuction(),issues=exportIssues(a),items=a.items.length,photos=a.items.reduce((sum,item)=>sum+(item.photos?.length||0),0);$("#exportSummary").innerHTML=`<div class="export-counts"><div><strong>${items}</strong><span>lots</span></div><div><strong>${photos}</strong><span>photos</span></div><div><strong>${issues.length}</strong><span>checks</span></div></div>${issues.length?`<div class="export-warnings"><strong>Review before publishing</strong><ul>${issues.slice(0,6).map(issue=>`<li>${esc(issue)}</li>`).join("")}${issues.length>6?`<li>and ${issues.length-6} more</li>`:""}</ul></div>`:`<div class="export-ready">✓ Catalog has the core fields needed for export</div>`}`}
function openExportDialog(){if(!currentAuction())return;renderExportSummary();$("#exportDialog").showModal()}
async function downloadCatalogPackage(e){e.preventDefault();const auction=currentAuction();if(!auction?.items.length)return showToast("Add an item before exporting");setBusy(true,"Building catalog ZIP…");try{await loadScript("https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js","JSZip");const platform=$("#exportPlatform").value,zip=new JSZip(),manifest=[["Lot Number","Photo Number","Filename"]];zip.file("catalog.csv",csv(platformCatalog(platform,auction)));zip.file("auction-settings.json",JSON.stringify({auction:{name:auction.name,type:auction.type,date:auction.date,location:auction.location},publishing:exportSettings()},null,2));for(const item of auction.items){for(let index=0;index<(item.photos||[]).length;index++){const name=`${item.lot}-${index+1}.jpg`;manifest.push([item.lot,index+1,name]);try{const blob=await (await fetch(item.photos[index])).blob();zip.file(`photos/${name}`,blob)}catch{}}}zip.file("photo-manifest.csv",csv(manifest));zip.file("README.txt",`HammerList catalog export\n\nDestination: ${$("#exportPlatform").selectedOptions[0].textContent}\nAuction: ${auction.name}\n\nFor Auction Flex: import catalog.csv, map the spreadsheet columns, and import the photos folder using lot-number filenames. Review auction-level settings in auction-settings.json before uploading to HiBid.\n\nFor other platforms: use catalog.csv as the platform-ready working file and confirm the current vendor template or authorized API requirements before publishing.`);const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}}),filename=`${safeName(auction.name)}-${platform}.zip`;if(isNative){const result=await Filesystem.writeFile({path:filename,data:await blobToBase64(blob),directory:Directory.Cache,recursive:true});await Share.share({title:`${auction.name} catalog`,text:"HammerList auction catalog package",files:[result.uri],dialogTitle:"Save or share catalog ZIP"});showToast("Catalog ZIP ready to save or share")}else{const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);showToast("Catalog ZIP downloaded")}$("#exportDialog").close()}catch(error){showToast(error.message||"The catalog package could not be created")}finally{setBusy(false)}}

$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();if($("#loginEmail").value.trim().toLowerCase()!=="auctioneer@hammerlist.app"||$("#loginPassword").value!=="demo123")return showToast("Use the demo credentials shown below the form");await Promise.race([stateReady,new Promise(resolve=>setTimeout(resolve,1200))]);if(!state)state=freshSeed();sessionStorage.setItem("hammerlist-session",$("#loginEmail").value.trim());startApp()});
function startApp(){$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#signedInEmail").textContent=sessionStorage.getItem("hammerlist-session")||"auctioneer@hammerlist.app";render()}
function logout(){sessionStorage.removeItem("hammerlist-session");$("#appView").classList.add("hidden");$("#loginView").classList.remove("hidden")}
$("#logoutBtn").onclick=logout;$("#profileBtn").onclick=logout;$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");$("#auctionSelect").onchange=async e=>{state.selectedAuctionId=e.target.value;await saveState();render()};
$$('.nav-item').forEach(b=>b.onclick=()=>{route=b.dataset.route;$("#sidebar").classList.remove("open");render()});
document.addEventListener("click",async e=>{const action=e.target.closest("[data-action]")?.dataset.action;if(action==="new-auction")openAuctionDialog();if(action==="add-item")openItem();if(action==="export")openExportDialog();if(action==="auctions"){route="auctions";render()}const auctionId=e.target.closest("[data-select-auction]")?.dataset.selectAuction;if(auctionId){state.selectedAuctionId=auctionId;route="dashboard";await saveState();render()}const itemId=e.target.closest("[data-item]")?.dataset.item;if(itemId)viewItem(itemId);const remove=e.target.closest("[data-remove-photo]")?.dataset.removePhoto;if(remove!==undefined){draftPhotos.splice(Number(remove),1);renderPhotoGrid()}const del=e.target.closest("[data-delete-item]")?.dataset.deleteItem;if(del)deleteItem(del);const close=e.target.closest("[data-close]")?.dataset.close;if(close)$("#"+close).close()});
$("#auctionForm").addEventListener("submit",createAuction);$("#cameraInput").onchange=e=>addFiles(e.target.files);$("#libraryInput").onchange=e=>addFiles(e.target.files);$("#vinCameraInput").onchange=e=>scanVinCamera(e.target.files);$("#scanBtn").onclick=()=>runAI("primary");$("#secondOpinionBtn").onclick=()=>runAI("secondary");$("#continueBtn").onclick=showDetailsStep;$("#backItemBtn").onclick=showPhotoStep;$("#closeItem").onclick=()=>$("#itemDialog").close();$$('input[name="itemKind"]').forEach(r=>r.onchange=()=>setItemKind(r.value));$("#itemCategory").onchange=()=>setItemKind($("#itemCategory").value==="Vehicles"?"vehicle":$("#itemCategory").value==="Farm Equipment"?"farm":"estate");$("#decodeVinBtn").onclick=decodeVin;$("#scanVinBtn").onclick=scanVin;$("#itemForm").addEventListener("submit",saveItem);$("#exportForm").addEventListener("submit",downloadCatalogPackage);$("#exportPlatform").onchange=renderExportSummary;$("#mobileAdd").onclick=openItem;
if(isNative){$("#takePhotoControl").addEventListener("click",event=>{event.preventDefault();takeNativeItemPhoto()});$("#choosePhotosControl").addEventListener("click",event=>{event.preventDefault();chooseNativeItemPhotos()});$("#vinPhotoControl").addEventListener("click",event=>{event.preventDefault();takeNativeVinPhoto()})}
const stateReady=loadState();stateReady.then(()=>{if(sessionStorage.getItem("hammerlist-session"))startApp()}).catch(()=>{state=freshSeed()});
